# Site settings
title: Invent.to - Soluções em Sistemas Computacionais
email: falecom@invent.to
description: "Invent.to - Soluções em Sistemas Computacionais - Desafio e inovação é o nosso negócio - Transformamos suas idéias em realidade."

baseurl: ""
url: "http://invent.to"

# Build settings
markdown: kramdown
permalink: pretty

