# Site settings
title: Invent.to - Soluções em Sistemas Computacionais
email: falecom@invent.to
description: "Invent.to - Soluções em Sistemas Computacionais - Desafio e inovação é o nosso negócio - Transformamos suas idéias em realidade."

baseurl: ""
url: "http://invent.to"

# Build settings
markdown: kramdown
permalink: pretty

encoding: utf-8


author:
  jonatas:
    display_name: Jônatas Paganini
    email: jonatas@invent.to
    web: http://ideia.me/
    twitter: jonatasdp
    github: jonatas
  mitrut:
    display_name: Wellington Mitrut
    gravatar: 278d0b5b8f680ac2a39bb3d8a6e21be3
    email: mitrut@invent.to
    web: http://wmitrut.github.io/
    twitter: wmitrut	
    github: wmitrut
  tafarel:
    display_name: José Luiz Tafarel
    gravatar: 6d422e42d26918052106c661cd19e9b7
    email: tafarel@invent.to
    web: http://jltafarel.github.io/
    twitter: jltafarel	
    github: jltafarel
